[[GoogleTest]]
arch = "aarch64"
git-tree-sha1 = "6a9b0c4e24fc743a5c547ddd9af3112522f004dc"
os = "macos"

    [[GoogleTest.download]]
    sha256 = "bf074960c344ce4ab35348048b1342ea41c32674a34a5c9823603ddb8b828320"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.aarch64-apple-darwin.tar.gz"
[[GoogleTest]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f889e790f0762747090cf1b752bd7c694c6af22"
libc = "glibc"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "ccff5cf3ce2f942d382552546e43558a368dc8e5cdc3119710c163136b160bea"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.aarch64-linux-gnu-cxx03.tar.gz"
[[GoogleTest]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44215816505c16ee6b0dc0a54b1e54b0ea7d2f7e"
libc = "glibc"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "5decf42809a01c1991a297016ccd12ab179166adaabd9f413224d4188280896b"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.aarch64-linux-gnu-cxx11.tar.gz"
[[GoogleTest]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "86a979180f82d2e79b7926212dfe8153f8d98743"
libc = "musl"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "ce0d00a9169b88a1a8f38e88839c1ae972d68d1acb5d90265eaa266a9cf115f1"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.aarch64-linux-musl-cxx03.tar.gz"
[[GoogleTest]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8068d7bd67ad7684d8878126de7b212880bb22b1"
libc = "musl"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "ae3803895f238185e9f304002b8a60725a8c503fe5a1e15411f8b83631fcc3ed"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.aarch64-linux-musl-cxx11.tar.gz"
[[GoogleTest]]
arch = "aarch64"
git-tree-sha1 = "1a2d180ffc42aa867ddd9de0062ee68f13501026"
os = "freebsd"

    [[GoogleTest.download]]
    sha256 = "bb55222e14cdfd2779fbbf2eb9dca2954c6b28105fa4037078130ace164723ff"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.aarch64-unknown-freebsd.tar.gz"
[[GoogleTest]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b664cf93c7153c4f85a214943f2703663e8f9835"
libc = "glibc"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "6223a790ba89f95e47e4515f21aa3b441e281a58b84d877577c2864c86b2e5e3"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[GoogleTest]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3987af4890527edc4c34c1b92f9124ae7c09e22"
libc = "glibc"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "6d73c613399307e907af8e9a6056ca8185fd6813fff1e6be280c0a8303847a02"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GoogleTest]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad5aa7926e27bca20fd41db34db8f32c0f4e017b"
libc = "musl"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "dcc12d1a3e8b6d0ac97b12267c1aa6bcbb32fbbb5d9f2a541ae94e0dfcbc01b8"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[GoogleTest]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7cecd581d764de64cdbd5f76694d589bd814000"
libc = "musl"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "f615366959336adf98629299bc98568fc45a4a45503e99325163ef078fb4fd76"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GoogleTest]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d0320fff98ae2baa8c8d6dec5b4d2225d034721"
libc = "glibc"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "82c5b858882dbbb17f32f4f89a7d6eef9454eff5994741900bde3f889390da3c"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[GoogleTest]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "723284873218c37b8b1e05d7d08d5816d152e7d5"
libc = "glibc"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "2fe9f6c14db2cdf72a7f30b9c1621dcf2c1440dd41c0f89fffe93c3f5fa3539f"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GoogleTest]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b4e2bf6f1dd811f8cfc5258e23f813ea4e0019a7"
libc = "musl"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "4f2de0a9d3fc1175995e5e6de4894dc79958c1d2d54f1038b6c3e65577ef2945"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[GoogleTest]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c904e60881dba7181e2d945b4a4945ff60fd79e0"
libc = "musl"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "2caccf9ec937a2799a6d89ab1a375c969c14a966f82219c4ffb574c78a0d18be"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GoogleTest]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d362bcc5da64182e3a75c7e219d5f76a09f50970"
libc = "glibc"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "e378ea10b98ef928ef6445eb8b550d936e3f435b0e8d547bae9314c308f4f251"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.i686-linux-gnu-cxx03.tar.gz"
[[GoogleTest]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bce50d2459f1c53e866320a7876241333c37068d"
libc = "glibc"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "6f2ae41bc013b5dfbfb24219d97f16e7451d82f729365b6b924264dfeacf0e0c"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.i686-linux-gnu-cxx11.tar.gz"
[[GoogleTest]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b499d846fd5cb7c128784be4e7a0c427e7556f48"
libc = "musl"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "50ffdc3d84bf9d7ddac821b7a5ae036f809b2ad6137e2fa0ffb2768be49deccd"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.i686-linux-musl-cxx03.tar.gz"
[[GoogleTest]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30ab55e39414b9e831e2849035112aa49b396285"
libc = "musl"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "ca098d88ae60ce134493744510bbf5f302ef2ecfea9dba1343766ed3c8bb1b02"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.i686-linux-musl-cxx11.tar.gz"
[[GoogleTest]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce093328c2b154446082192f75cb46b8122a9408"
os = "windows"

    [[GoogleTest.download]]
    sha256 = "1fc833d0b96df7c2f35cc685d17db510ec528a0ece9ad9b16056e4375b2fcd60"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.i686-w64-mingw32-cxx03.tar.gz"
[[GoogleTest]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb80486aa1467772810eba574815b591c89eda55"
os = "windows"

    [[GoogleTest.download]]
    sha256 = "c4560b0fb006a00a6ef59ea11a11e3589a6696936411ad709ec074c22093a4bd"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.i686-w64-mingw32-cxx11.tar.gz"
[[GoogleTest]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a21b9bbec6dc3255dea3fe0cefff277082d1c17e"
libc = "glibc"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "42d58ef7c46db7fcc4c69897f5f0fddc41b38c47170b42a8bb217d16802013bd"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GoogleTest]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dcd67dafd8cefb355ceb6fcd43844eae3e8d9cf3"
libc = "glibc"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "a8736d06ff7cbe9c647565b1e0086fea8a0ed98e5d0ff19f284c0a74c338a078"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GoogleTest]]
arch = "x86_64"
git-tree-sha1 = "00cca1f076bd3b32b267a43e48c78af4c2654594"
os = "macos"

    [[GoogleTest.download]]
    sha256 = "f029858f4b175e08de8ea5d83ab21d74bc9ac0893b99a754e3921137be9831b3"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.x86_64-apple-darwin.tar.gz"
[[GoogleTest]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f7d7c4ef3dbc365dbcce514a3965a64413adc946"
libc = "glibc"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "a3dc81f067a529c215f72ec63e8460f5e757b408ebc12224bca417c060e5587b"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.x86_64-linux-gnu-cxx03.tar.gz"
[[GoogleTest]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1d44897de63b8c11a7358b0b0dcf939e733a44f"
libc = "glibc"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "0ddc8da32dfa2d599b05a85c85f4f844a66fa70c0e026112293be9300454b12e"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.x86_64-linux-gnu-cxx11.tar.gz"
[[GoogleTest]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a683fb629214ea9733c5ac98b086f7a17e39e6aa"
libc = "musl"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "5a827604ddb212493bc2998601582ee43ef858ce57badf80401723671881faee"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.x86_64-linux-musl-cxx03.tar.gz"
[[GoogleTest]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e35ec55e4d52c84ac4a7586a52a62dc84e2f7396"
libc = "musl"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "b6c617adfb73fbdb4090dc815bd45b8c20f12100b6ef2293fccc6efe1bd34320"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.x86_64-linux-musl-cxx11.tar.gz"
[[GoogleTest]]
arch = "x86_64"
git-tree-sha1 = "9c8786e6b49dd7a9788c9164db89de6e2d7d1793"
os = "freebsd"

    [[GoogleTest.download]]
    sha256 = "e93afe72789e0280a7ea08592b3a1a7bfcdcc616f51712fbf71e0824f3b9f5bd"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.x86_64-unknown-freebsd.tar.gz"
[[GoogleTest]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e6a63ae0c0b3ea96e05e0eff55b8e443a43f16f"
os = "windows"

    [[GoogleTest.download]]
    sha256 = "887078dbfab35f12954ffb9c20d0a5533fbcc220d97324c641d693dfa3479e9f"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[GoogleTest]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f662aecbf10a5f7445d76a02f008f2f801abf4a"
os = "windows"

    [[GoogleTest.download]]
    sha256 = "5f81ae424ddf778383d4baf01d5f3f06e2c553d38d9d7e47e6fc55f525c12140"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+1/GoogleTest.v1.11.0.x86_64-w64-mingw32-cxx11.tar.gz"
