[[GoogleTest]]
arch = "aarch64"
git-tree-sha1 = "6ab98288b1ee8d8a2277d6a5524c661f08912343"
os = "macos"

    [[GoogleTest.download]]
    sha256 = "c99bb7021b7962b7d238a07dbbdb953e04f1d6fb3e7c2f930f50ea1f95def116"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.aarch64-apple-darwin.tar.gz"
[[GoogleTest]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7fbf80e1567fdd584442d5e5682f35073c36852a"
libc = "glibc"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "a1e7ebac475da842b2699b9efc6e863d7c6b4b78c260662486b80283722e387f"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.aarch64-linux-gnu-cxx03.tar.gz"
[[GoogleTest]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "265872f716ff7d173245676642033d3605cf21b0"
libc = "glibc"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "dd4511c5ca18d8c1db9f11c3bd2eec3169ac0cd3f6899707f8d9779beb2105db"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.aarch64-linux-gnu-cxx11.tar.gz"
[[GoogleTest]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5e27acfb78b7cb1960e1d6753f6e1ae31b3a6852"
libc = "musl"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "71005ec1452895ad144bb42b7abcd8652be93128798754df67e6027883e61036"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.aarch64-linux-musl-cxx03.tar.gz"
[[GoogleTest]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c95b60e4358c113782ac2920e0fc3cbe15874b06"
libc = "musl"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "7e45c8154801e10622dcd37219165d0dbd71f3b495f3cf30a4dc5c5de58698d4"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.aarch64-linux-musl-cxx11.tar.gz"
[[GoogleTest]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "883c08e1210797d71cc516ccaffe3353430056b0"
libc = "glibc"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "4cf7535b36c0b5037f3ec22d98916cbdc8f8e8552ae93dee2e65ae373c7c2120"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[GoogleTest]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "890eb07701004888a15643464bb843fab3a81a27"
libc = "glibc"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "7e50b159b5fbbb66d412604e377a4d6e3bf5f727a9c3c6eb511daaadd2187d28"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GoogleTest]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "24c3b7f49faa10cc962e09c2fb61a90aaa09bd11"
libc = "musl"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "d512bfe22dab70a6820cc426ca0e77b38ff7ff2981ad90e01ce6d7e560ef9303"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[GoogleTest]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b03b1108f6fb6f1e2094c65e7fefe1851d9bac8"
libc = "musl"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "b828b85cf54736420d31c41535934246f243e4ebd8af638c7363b21405931b66"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GoogleTest]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33e3a2609cb9f4029af42a31612c82cebb155ef9"
libc = "glibc"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "022da34adae51e7856c415e28aedf061ac99a6f5b0e91268a410fac47825a073"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[GoogleTest]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "165cce233e6177cd42506b7f4a7a7cb534f241e3"
libc = "glibc"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "6cb73b0f14e6d342f88a4741e61e0a46904019c40afe157f196fbcab9f6c0902"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GoogleTest]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8c202f665b33da19940df2b70748b590a05506bd"
libc = "musl"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "3a3c2d9d7df42e76f06a1f36c54b6f30f31c7d05c5e9d970293e7cf4608da3e3"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[GoogleTest]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d9850984c03d9f503b418dbfc9b4fd2d77e4fc9"
libc = "musl"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "37794be812a98cdf3275d5131a28880853bc81acac805de4debb94604442ef4b"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GoogleTest]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "626ba998e60b072d5aad401f3170ace3b8a76354"
libc = "glibc"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "2f8779ac04ea5f26bc0855bec2cfaf0a8ef19ddd8540a5c1de4babe0ac42f1e0"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.i686-linux-gnu-cxx03.tar.gz"
[[GoogleTest]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d69538ef4a7dcc8741ab4f3ab4de756dc76b2474"
libc = "glibc"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "2be7e3708c2881fa1c3e5c1603331aa87f5bd219cd71c69577e9c744c323181d"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.i686-linux-gnu-cxx11.tar.gz"
[[GoogleTest]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af01a3b3c7a4e364d496896aea3ca6e2ea1f71f9"
libc = "musl"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "19d57f4aebbad6b5bb09bf5ef18508882ed428dc27a6e01bc9a4e355e00fddf5"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.i686-linux-musl-cxx03.tar.gz"
[[GoogleTest]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f145345ad21cf09404308c10f4417d9ebddc026c"
libc = "musl"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "7ef5e27066b9f32eb79e7aaed2b4803779cc0800f033d68c8cd6fefc7eda686b"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.i686-linux-musl-cxx11.tar.gz"
[[GoogleTest]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38b059d63953e9dce1db6e875f0e40f2bdfc3dfc"
os = "windows"

    [[GoogleTest.download]]
    sha256 = "610a7ef01edf5b615e3bf59a680ab05ea02c0fcf0411a1a299ee71d028b1e0e7"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.i686-w64-mingw32-cxx03.tar.gz"
[[GoogleTest]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "632f6c83c928ae5a3b0bf964a9a1e8e99213c044"
os = "windows"

    [[GoogleTest.download]]
    sha256 = "48ee94130632c03cf6ff7c2f689a10c3b2cad234baa6a448ab6dff04267a1d5c"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.i686-w64-mingw32-cxx11.tar.gz"
[[GoogleTest]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7308092e672a79fdbf084db45844be363a5ba834"
libc = "glibc"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "fb268c80b59b40f9cf67498b5b436e35cae4a07483ba168a67a027c89e0c9485"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GoogleTest]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10fa2994ae88b48c8f4718a50bfea3050beb5db8"
libc = "glibc"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "5362143a6055652728632a8b224ee4e84415031803fd9d20498031dd180b5f5b"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GoogleTest]]
arch = "x86_64"
git-tree-sha1 = "4d086196aedc4aea393b904bcf30e3e5fd22781b"
os = "macos"

    [[GoogleTest.download]]
    sha256 = "d2da3a4fce947315bbf399c2cf9f031fb573c57f38316804658b66524387f3eb"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.x86_64-apple-darwin.tar.gz"
[[GoogleTest]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "53155f2d1fa6f1c8c0413443fa6ad2c8a589d47f"
libc = "glibc"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "70405acf5bef6c0f52db4c4cf6bb9ee8393bcb952224f53f7969ed2ef8ce8201"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.x86_64-linux-gnu-cxx03.tar.gz"
[[GoogleTest]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d1c3949a4f9f7e57ebb3d95de3b2c2fca99bf52c"
libc = "glibc"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "51b17713468349b97439df0d094ab3f87a19850b4f918efb24a8f35ca8cabbc7"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.x86_64-linux-gnu-cxx11.tar.gz"
[[GoogleTest]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "627b518777eda78f64898fa46d9ab4b566584bd3"
libc = "musl"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "44074cf7a438b41f71f227c185f0a4cfeca0dde000782013370789c246eafb49"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.x86_64-linux-musl-cxx03.tar.gz"
[[GoogleTest]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8cbaf92cec3f6160d8fd6badff194d7478bdf60e"
libc = "musl"
os = "linux"

    [[GoogleTest.download]]
    sha256 = "8a11026f08c84d503c3ce06e3e7bd8762e2194498380b748464c303a8053c309"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.x86_64-linux-musl-cxx11.tar.gz"
[[GoogleTest]]
arch = "x86_64"
git-tree-sha1 = "427e3b165e2d0f78dd05750f2235dc9cdf5cb10c"
os = "freebsd"

    [[GoogleTest.download]]
    sha256 = "9128892376bbd26f668a37e03744781e10b559216ff2ee76576d2cedf117ab90"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.x86_64-unknown-freebsd.tar.gz"
[[GoogleTest]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7577c2c5668466a05318dff0503841cdc632c27a"
os = "windows"

    [[GoogleTest.download]]
    sha256 = "d44820382d90a9545f808286525eea31fe3a933c4fff4fc62df717ab976ea1f6"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[GoogleTest]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73cda5ba62ad7e3a1a3421f2402eb6f902ba3ae0"
os = "windows"

    [[GoogleTest.download]]
    sha256 = "6d3243a950f645e914fe015d205da2b80064c5d73da53efa9ff6e0d8a5f2009c"
    url = "https://github.com/JuliaBinaryWrappers/GoogleTest_jll.jl/releases/download/GoogleTest-v1.11.0+0/GoogleTest.v1.11.0.x86_64-w64-mingw32-cxx11.tar.gz"
