# Autogenerated wrapper script for GoogleTest_jll for aarch64-apple-darwin
export libgmock, libgmock_main, libgtest, libgtest_main

JLLWrappers.@generate_wrapper_header("GoogleTest")
JLLWrappers.@declare_library_product(libgmock, "@rpath/libgmock.1.11.0.dylib")
JLLWrappers.@declare_library_product(libgmock_main, "@rpath/libgmock_main.1.11.0.dylib")
JLLWrappers.@declare_library_product(libgtest, "@rpath/libgtest.1.11.0.dylib")
JLLWrappers.@declare_library_product(libgtest_main, "@rpath/libgtest_main.1.11.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libgmock,
        "lib/libgmock.1.11.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgmock_main,
        "lib/libgmock_main.1.11.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgtest,
        "lib/libgtest.1.11.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgtest_main,
        "lib/libgtest_main.1.11.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
